- hosts: localhost
  become: yes

- import_playbook: system/core.yml
- import_playbook: system/dotfiles.yml
- import_playbook: system/fonts.yml
- import_playbook: system/oh-my-posh.yml
- import_playbook: system/gnome.yml

- import_playbook: node/core.yml

- import_playbook: vscode/core.yml
