- name: "Install new dev pc"
  hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False

- import_playbook: system/core.yml
- import_playbook: system/oh-my-posh.yml
- import_playbook: system/dotfiles.yml
- import_playbook: system/fonts.yml

- import_playbook: languages/node/core.yml

- import_playbook: applications/vscode/core.yml
- import_playbook: applications/browsers/chrome/core.yml
- import_playbook: applications/browsers/firefox/core.yml
- import_playbook: applications/slack/core.yml
- import_playbook: applications/spotify/core.yml

- import_playbook: system/gnome.yml
