- name: Install packages
  hosts: localhost
  become: yes

  vars:
    - package_name: firefox

  tasks:
    - name: "Check if {{ package_name }} is installed"
      command: "dpkg-query -W {{ package_name }}"
      register: my_package_check_deb
      failed_when: my_package_check_deb.rc > 1
      changed_when: my_package_check_deb.rc == 1
    - name: "Install {{ package_name }}"
      apt:
        name: "{{ package_name }}"
        state: latest
      when: my_package_check_deb.rc == 1
