- name: Dotfiles configuration
  hosts: localhost
  become: yes

  vars:
    - user: "jansek"
    # - dotfiles_repo: "git@github.com:C-Jansek/.dotfiles.git"
    # - ssh_key: ".ssh/id_ed25519"

  tasks:
    # Copy configuration files
    - name: "Sync config files"
      ansible.posix.synchronize:
        src: "~/tmp-dotfiles/dotfiles"
        dest: /home/{{ user }}/
