- name: Dotfiles configuration
  hosts: localhost
  become: yes

  vars:
    - user: "jansek"
    - dotfiles_repo: "git@github.com:C-Jansek/.dotfiles.git"
    - ssh_key: ".ssh/id_ed25519"

  tasks:
    - name: "check if can reach git"
      shell: "ssh -T git@github.com"
    # - name: "Check out dotfiles from repository"
    #   git:
    #     repo: "{{ dotfiles_repo }}"
    #     dest: "/home/{{ user }}/tmp-dotfiles"
    #     #     clone: yes
    #     #     accept_hostkey: yes
    #     key_file: "/home/{{ user }}/{{ ssh_key }}"
    #     version: master
    #   delegate_to: localhost
    #   run_once: true
    #   become: no

    #   # Copy configuration files
    # - name: "Sync config files"
    #   ansible.posix.synchronize:
    #     src: ./tmp-dotfiles/dotfiles
    #     dest: /home/{{ user }}/
