- name: Install fonts
  hosts: localhost
  become: yes

  vars:
    user: "jansek"
    hack_zip: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Hack.zip
#     fonts:
#       # FiraCode Nerd Font
#       - https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/FiraCode/Regular/complete/Fira%20Code%20Regular%20Nerd%20Font%20Complete%20Mono.ttf
#       - https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/FiraCode/Bold/complete/Fira%20Code%20Bold%20Nerd%20Font%20Complete%20Mono.ttf
#       - https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/FiraCode/Light/complete/Fira%20Code%20Bold%20Nerd%20Font%20Complete%20Mono.ttf
#       - https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/FiraCode/Medium/complete/Fira%20Code%20Bold%20Nerd%20Font%20Complete%20Mono.ttf
#       - https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/FiraCode/SemiBold/complete/Fira%20Code%20Bold%20Nerd%20Font%20Complete%20Mono.ttf
#       - https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/FiraCode/Bold/complete/Fira%20Code%20Bold%20Nerd%20Font%20Complete%20Mono.ttf
#       # Hack Nerd Font
#       - https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Hack/Regular/complete/Hack%20Regular%20Nerd%20Font%20Complete%20Mono.ttf
#       - https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Hack/Regular/complete/Hack%20Regular%20Nerd%20Font%20Complete.ttf
#       - https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Hack/Bold/complete/Hack%20Bold%20Nerd%20Font%20Complete%20Mono.ttf
#       - https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Hack/Bold/complete/Hack%20Bold%20Nerd%20Font%20Complete.ttf
#       - https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Hack/Italic/complete/Hack%20Regular%20Nerd%20Font%20Complete%20Mono.ttf
#       - https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Hack/Italic/complete/Hack%20Regular%20Nerd%20Font%20Complete.ttf
#       - https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Hack/BoldItalic/complete/Hack%20Bold%20Nerd%20Font%20Complete%20Mono.ttf
#       - https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Hack/BoldItalic/complete/Hack%20Bold%20Nerd%20Font%20Complete.ttf

  tasks:
    - name: Ensure fonts directory exists
      file:
        path: "{{ lookup('env', 'HOME') }}/.fonts"
        state: directory

    - name: Font exists
      shell: "ls {{ lookup('env', 'HOME') }}/.fonts/Hack*Nerd*Font*Complete*"
      register: hack_exists
      ignore_errors: yes

    - name: Download Hack
      when: hack_exists is failed
      ansible.builtin.unarchive:
        src: "{{ hack_zip }}"
        dest: "{{ lookup('env', 'HOME') }}/.fonts/"
        remote_src: yes
      register: fonts_downloaded

    - name: Update font cache
      become: yes
      command: fc-cache -sv
      when: fonts_downloaded.changed

    - name: Update APT package list
      become: yes
      apt:
        update_cache: yes
      when: apt_repository.changed
      register: apt_update
      retries: 5
      until: apt_update is success
